### ISSUE TITLE
Windows - Startup fails on Sasquatch 06/2021 Release

### ISSUE THREAD

**Issue by sarapayne** [OpenSim-NGC/OpenSim-Sasquatch#35]
Windows start also fails but in a very different way to Linux. I get the same result on a self-build and the binary downloaded from Github. The configuration is exactly the same as the one I am using on Linux, but this build is looking for items in folders I don't have, somewhere there is a hardcoded path I am guessing. 

`17:27:02 - Fatal error: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The system cannot find the file specified.
   at NSL.Certificate.Tools.NSLCertificateVerify..ctor()
   at OpenSim.Region.OptionalModules.Currency.DTLNSLMoneyModule..ctor() in D:\Documents\Projects\UtopiaSkye\OpenSim-NGC\OpenSim-Sasquatch\addon-modules\OpenSim.Region.OptionalModules.Currency\OpenSim.Region.OptionalModules.Currency\DTLNSLMoneyModule.cs:line 223
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at OpenSim.ApplicationPlugins.RegionModulesController.RegionModulesControllerPlugin.Initialise(OpenSimBase openSim) in D:\Documents\Projects\UtopiaSkye\OpenSim-NGC\OpenSim-Sasquatch\OpenSim\ApplicationPlugins\RegionModulesController\RegionModulesControllerPlugin.cs:line 150
   at OpenSim.Framework.PluginLoader`1.Load() in D:\Documents\Projects\UtopiaSkye\OpenSim-NGC\OpenSim-Sasquatch\OpenSim\Framework\PluginLoader.cs:line 189
   at OpenSim.OpenSimBase.LoadPlugins() in D:\Documents\Projects\UtopiaSkye\OpenSim-NGC\OpenSim-Sasquatch\OpenSim\Region\Application\OpenSimBase.cs:line 197
   at OpenSim.OpenSimBase.StartupSpecific() in D:\Documents\Projects\UtopiaSkye\OpenSim-NGC\OpenSim-Sasquatch\OpenSim\Region\Application\OpenSimBase.cs:line 284
   at OpenSim.OpenSim.StartupSpecific() in D:\Documents\Projects\UtopiaSkye\OpenSim-NGC\OpenSim-Sasquatch\OpenSim\Region\Application\OpenSim.cs:line 179
   at OpenSim.Framework.Servers.BaseOpenSimServer.Startup() in D:\Documents\Projects\UtopiaSkye\OpenSim-NGC\OpenSim-Sasquatch\OpenSim\Framework\Servers\BaseOpenSimServer.cs:line 204`

**Comment by sarapayne** [comment]
fixed by @mdickson  before commit [e8d271f](https://github.com/OpenSim-NGC/OpenSim-Sasquatch/commit/e8d271fd92e9a2f33e61162bfec9eb12eae58f68)
